# frozen_string_literal: true

gem 'jekyll', '~>4.1.1'

group :plugins do
  gem 'jekyll-feed', '~>0.15.1'
  gem 'jekyll-seo-tag', '~>2.6.1'
  gem 'jekyll-sitemap', '~>1.4.0'
end

source 'https://rubygems.org'
