jobs:
  release:
    name: release
    runs-on: ubuntu-20.04
    steps:
      - name: git_checkout
        uses: actions/checkout@v2.3.3

name: release

on:
  push:
    branches:
      - main
    tags:
      - '*'
